# Generated by Django 4.1.4 on 2023-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Online Payment', 'Online Payment'), ('Cash', 'Cash'), ('Pending', 'Pending'), ('Credit', 'Credit')], default='Pending', max_length=50),
        ),
    ]
