# Generated by Django 4.1.4 on 2023-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Pending', 'Pending'), ('Cash', 'Cash'), ('Online Payment', 'Online Payment')], default='Pending', max_length=50),
        ),
    ]
