# Generated by Django 4.1.6 on 2023-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Online Payment', 'Online Payment'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
