# Generated by Django 4.1.4 on 2023-08-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Pending', 'Pending'), ('Online Payment', 'Online Payment')], default='Pending', max_length=50),
        ),
    ]
