# Generated by Django 4.1.4 on 2023-08-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment'), ('Pending', 'Pending'), ('Credit', 'Credit')], default='Pending', max_length=50),
        ),
    ]
