# Generated by Django 4.1.4 on 2023-08-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_billing_status_alter_billing_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Online Payment', 'Online Payment'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
